services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      UVICORN_CMD: "uvicorn server:app --host 0.0.0.0 --port 8000"

  frontend:
    build:
      context: ./bossypaints
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      BOSSYPAINTS_API_URL: "http://backend:8000"
    depends_on:
      - backend
