name: Deploy to Production
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Docker Compose to Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create pem
        run: echo "${{ secrets.DEPLOY_PEM }}" > deploy.pem && chmod 400 deploy.pem

      - name: SSH and deploy
        run: ssh -i deploy.pem ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "cd [PROJECT_DIR] && git pull origin main && docker-compose up -d --build"
